import "@/styles/globals.css";
import type { Metadata } from "next";
import { type ReactNode } from "react";
import { Providers } from "./providers";
import Header from "@/app/components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Jagantara",
  description: "Generated by create-wagmi",
  icons: "/jagantara_icon.png",
};

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          {props.children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
