import "./globals.css";
import type { Metadata } from "next";
import { type ReactNode } from "react";
import { Providers } from "./providers";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Jagantara",
  description: "Generated by create-wagmi",
};

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          {props.children}
        </Providers>
      </body>
    </html>
  );
}
